---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(lubridate)
```

```{r read and select ars flux data}
ars_fluxes<-read_csv("../data/ars_fluxes.csv", skip = 2)

fluxes<-ars_fluxes%>%
  select(`Experimental Unit ID`, Date, N2O, Air_Temp, Soil_Temp, Soil_Moisture)%>%
  mutate(Date = mdy_hms(Date))%>%
  separate(`Experimental Unit ID`, c("state","exp"), sep = 3)

head(fluxes)
```

```{r read and select ars weather data}
ars_weather<-read_csv("../data/ars_weather.csv", skip = 2)

weather<-ars_weather%>%
  select(`Site ID`, Date, `Temperate, air, daily, maximum, degrees Celsius`, `Temperate, air, daily, minimum, degrees Celsius`, Precip, `Total_Net_Radn`)%>%
  mutate(Date = mdy_hms(Date))%>%
  separate(`Site ID`, c("state","exp"), sep = 3)%>%
  filter(state != "ORP")

head(weather)
```
```{r read and select daymet ars data}
daymet_mandan<-read_csv("../data/daymet_mandan.csv", skip = 7)
daymet_mandan$town<-"Mandan"
daymet_morris<-read_csv("../data/daymet_morris.csv", skip = 7)
daymet_morris$town<-"Morris"
daymet_roseville<-read_csv("../data/daymet_roseville.csv", skip = 7)
daymet_roseville$town<-"Roseville"
daymet_university_park<-read_csv("../data/daymet_university_park.csv", skip = 7)
daymet_university_park$town<-"University_Park"
daymet_west_lafayette<-read_csv("../data/daymet_west_lafayette.csv", skip = 7)
daymet_west_lafayette$town<-"West_Lafayette"

daymet<-rbind(daymet_mandan, daymet_morris, daymet_roseville, daymet_university_park, daymet_west_lafayette)

daymet$date<-as.Date(strptime(paste(daymet$year, daymet$yday), format="%Y%j"))
colnames(daymet)<-c("year", "yday", "daymet_prcp", "daymet_radn", "daymet_tmax", "daymet_tmin", "town", "date")

head(daymet)
```


```{r join and filter fluxes and weather data}
ars<-full_join(weather, fluxes, by=c("state", "Date"))

colnames(ars)<-c("site", "nada", "date", "max_temp", "min_temp", "precip", "radn", "exp", "N2O", "air_temp", "soil_temp", "soil_moisture")

head(ars)
```
```{r check these data out}

ggplot(fluxes, (aes(x = state, y = N2O)))+
  geom_jitter(alpha = .3)
```

```{r look for sites that arent cold enough}
ggplot(ars, (aes(x = date, y = max_temp)))+
  geom_point(alpha = .3)+
  geom_hline(yintercept=0)+
  facet_wrap(~site)
```
```{r remove warm sites}
ars_cold<-ars %>% filter(site %in% c("INA", "INT", "INW", "MNM", "MNR", "NDM", "NEM", "NVN", "PAH"))%>%
   mutate(town = ifelse((site %in% c("INA", "INT", "INW")), "West_Lafayette",
                        ifelse((site == "MNM"), "Morris",
                               ifelse((site == "MNR"), "Roseville",
                                      ifelse((site %in% c("NDM", "NEM", "NVN")), "Mandan",
                                            ifelse((site == "PAH"), "University_Park", "NA"                                                                                           ))))))%>%
  mutate(month=month(date, label=TRUE), year = as.factor(year(date)))%>%
  filter(N2O < 1500 | is.na(N2O)) 

ggplot(ars_cold, (aes(x = date, y = max_temp)))+
  geom_point(alpha = .2)+
  geom_hline(yintercept=0)+
  facet_wrap(~town)
```

```{r cold fluxes}
ggplot(ars_cold, (aes(x = town, y = N2O)))+
  geom_jitter(alpha = .3)
```
```{r N20 over the years}
ggplot(ars_cold, (aes(x = date, y = N2O)))+
  geom_point(alpha = .3)+
  facet_wrap(~town, scales = "free")
``` 
```{r N2O by month}
ggplot(data = filter(ars_cold, month %in% c("Jan", "Feb", "Mar", "Apr", "May")) , aes(x=month, y=N2O, color = year))+
  geom_boxplot()+
  facet_wrap(~town, scales = "free", nrow=5)
```

```{r N2O and radiation in Mandan}
ggplot(data=filter(ars_cold, town == "Mandan", air_temp != "NA"), aes(x=air_temp, y=N2O, color = year))+
  geom_jitter(alpha=.3)#+
 # facet_wrap(~year, scales = "free")
head(ars_cold)
```

```{r narrow down to spring}
ars_spring<-ars_cold%>% filter(month %in% c("Jan", "Feb", "Mar", "Apr", "May"))

head(ars_spring)

```

```{r spring N20}
ggplot(data = group_by(ars_spring, year)%>%filter(town == "Morris") , aes(x=date, y=N2O))+
  geom_point()+
  facet_wrap(~year)
```